export { default as SplashScreen } from './SplashScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Tabs } from '../navigator/Tabs'
export {default as Home} from './TabScreen/HomeScreen/Home'
export {default as Bookings}  from './TabScreen/Bookings'
export {default as More}  from './TabScreen/More'
export {default as Likes} from './MoreTabs/Likes'
export {default as Settings} from './MoreTabs/Settings'
export {default as Payment} from './MoreTabs/Payment'
export {default as FavoriteHotels} from './MoreTabs/FavoriteHotels'
export {default as ProfileSetting} from './MoreTabs/ProfileSetting'
export {default as BookingScreenHotel} from './BookingScreenHotel'
export {default as ConfirmationScreen} from './ConfirmationScreen'
export {default as DetailsScreen} from './DetailsScreen'